services:
  # TLDraw container in development mode
  tldraw:
    build:
      context: ./tldraw
      dockerfile: Dockerfile
      args:
        BUILD_MODE: development
    container_name: tldraw-app-dev
    environment:
      - BUILD_MODE=development
    volumes:
      # Mount individual source files for live reloading in dev mode
      - ./tldraw/main.jsx:/app/main.jsx:ro
      - ./tldraw/index.html:/app/index.html:ro
      - ./tldraw/vite.config.js:/app/vite.config.js:ro
      # Don't mount node_modules or other build artifacts
    restart: unless-stopped